### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by L-as** [listentolist/kakoune-rainbow#1]
I am not quite sure how to debug this. I checked \*debug\*, I have all the dependencies and guile installed, I required the module, I ran :rainbow, but nothing happens? How can I debug this?

**Comment by listentolist** [comment]
@L-as That shouldn't happen...
You don't even get the error "no such command: rainbow"?
Do you use plug.kak or did you just put the plugin into autoload?
What is the output of `which guile` and `guile --version`?
Does connect.kak work? Try this:
`connect-shell %{ sleep 1; send echo yes }`
That should output `yes` after one second.
What is the output of `echo %opt{rainbow_path}`?
As a minimal test, just type `()` into the scratch buffer and run `rainbow`. The parentheses should turn red.

**Comment by L-as** [comment]
I have the command rainbow after I `:require-module rainbow`, and I did just put it all in my autoload. guile is version 2.2.7. connect-shell *does* work, I even use it normally, and rainbow_path is the path to where the this repository is stored.

**Comment by L-as** [comment]
And :rainbow still does absolutely nothing, even in a buffer with just ().

**Comment by listentolist** [comment]
Okay, what is the output of `which guile`? In the Guile script of this plugin it uses the location `/usr/bin/guile`. Maybe you've got it installed in another location.

**Comment by L-as** [comment]
Oh! That must be the reason. I am using NixOS, so it's in an entirely different location.

**Comment by listentolist** [comment]
Okay, then you could try to change the first line of `bin/kak-rainbow.scm` according to `which guile`. Does it work then?
