### ISSUE TITLE
Implementation of connect.kak changed

### ISSUE THREAD

**Issue by alexherbo2** [listentolist/kakoune-rainbow#3]
### Example 1

``` kak
$ echo 1 2 3
```

### Example 2

``` kak
$ sh -c %{
  echo "$1" "$2" "$3"
} -- 1 2 3
```

**Note**: The **$** is a Kakoune command.

**Comment by alexherbo2** [comment]
All connect commands are now prefixed with a **:** too, e.g. `get` → `:get`.

**Comment by listentolist** [comment]
Thank you! I updated the connect commands.
